### ISSUE TITLE
Integration tests are failing on CI

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud-stream-app-starters/counter#1]

**Comment by artembilan** [comment]
The symptoms looks like:
```
java.lang.NullPointerException
	at org.springframework.cloud.stream.app.counter.sink.CounterSinkDefaultNameTests.testIncrement(CounterSinkDefaultNameTests.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```
